version: "3.9"
services:
  db:
    image: postgres:13
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
